# Generated by Django 2.1 on 2018-08-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=16)),
                ('password', models.TextField(max_length=256)),
                ('status', models.BooleanField(default=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
