# Generated by Django 2.1 on 2018-08-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180821_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.AddField(
            model_name='card',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.TextField(max_length=16, unique=True),
        ),
    ]
