# Generated by Django 2.1 on 2018-08-22 07:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20180822_1010'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='card',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
