# Generated by Django 2.1 on 2018-08-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20180822_1013'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='card',
            managers=[
            ],
        ),
    ]
