# Generated by Django 2.1 on 2018-08-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cash_value',
            field=models.IntegerField(default=0),
        ),
    ]
